site_name: prefect-shell
site_url: https://PrefectHQ.github.io/prefect-shell
repo_url: https://github.com/PrefectHQ/prefect-shell
edit_uri: edit/main/docs
theme:
  name: material
  favicon: img/favicon.ico
  palette:
    primary: blue
    accent: blue
  icon:
    repo: fontawesome/brands/github
  logo: img/prefect-logo-mark-solid-white-500.png
  font:
    text: Inter
    code: Source Code Pro
extra_css:
    - stylesheets/extra.css
markdown_extensions:
    - admonition
    - attr_list
    - codehilite
    - md_in_html
    - meta
    - pymdownx.highlight:
        use_pygments: true
    - pymdownx.superfences
    - pymdownx.tabbed
plugins:
  - search
  - gen-files:
      scripts:
        - docs/gen_ref_pages.py
  - mkdocstrings:
      handlers:
        python:
          options:
            show_root_heading: True
            show_object_full_path: False
            show_category_heading: True
            show_signature: False
            show_bases: True
            heading_level: 1
watch:
    - prefect_shell/
    - README.md

nav:
    - Home: index.md
    - Commands: commands.md

