name: Tests

on: [pull_request]

jobs:
  run-tests:
    name: Run Windows Tests
    runs-on: windows-latest
    strategy:
      matrix:
        python-version:
          # Prefect Core only tests Windows against 3.9 currently.
          - "3.9"
          - "3.10"
      fail-fast: false
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
          cache-dependency-path: requirements*.txt

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade --upgrade-strategy eager -e ".[dev]"

      - name: Run tests
        env:
          PREFECT_ORION_DATABASE_CONNECTION_URL: "sqlite+aiosqlite:///./orion-tests.db"
        run: |
          pytest tests -vv
